export const FETCH_COUNTRY = 'FETCH_COUNTRY';
export const FETCH_COUNTRY_SUCCESS = 'FETCH_COUNTRY_SUCCESS';
export const FETCH_COUNTRY_FAILED = 'FETCH_COUNTRY_FAILED';

export const GET_COUNTRY_DATA = 'GET_COUNTRY_DATA';
export const GET_COUNTRY_DATA_SUCCESS = 'GET_COUNTRY_DATA_SUCCESS';
export const GET_COUNTRY_DATA_FAILED = 'GET_COUNTRY_DATA_FAILED';

export const GET_TOP_10_COUNTRIES = 'GET_TOP_10_COUNTRIES';
export const GET_TOP_10_COUNTRIES_SUCCESS = 'GET_TOP_10_COUNTRIES_SUCCESS';
export const GET_TOP_10_COUNTRIES_FAILED = 'GET_TOP_10_COUNTRIES_FAILED';

export const SET_COUNTRY_SELECTING = 'SET_COUNTRY_SELECTING';
