export const FETCH_HISTORICAL_DATA = 'FETCH_HISTORICAL_DATA';
export const FETCH_HISTORICAL_DATA_SUCCESS = 'FETCH_HISTORICAL_DATA_SUCCESS';
export const FETCH_HISTORICAL_DATA_FAILED = 'FETCH_HISTORICAL_DATA_FAILED';

export const SET_CHART_DATA = 'SET_CHART_DATA';